spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: false
        web-allow-others: false
logging.level.org.springframework: info
#security:
#  user:
#    name: user
#    password: senha