spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        path: /h2-console
        enabled: true
        settings:
          trace: false
          web-allow-others: false
logging.level.org.springframework: info
security:
  user:
    name: user
    password: senha